# Generated by Django 5.0.3 on 2024-03-07 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicle_brand", "0001_initial"),
        ("vehicle_type", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                ("year", models.PositiveIntegerField(verbose_name="Year")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=15, verbose_name="Price"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/vehicles",
                        verbose_name="Image",
                    ),
                ),
                (
                    "heading_title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Heading Title",
                    ),
                ),
                (
                    "heading_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Heading Description"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="vehicle_brand.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicle_type.type",
                        verbose_name="Vehicle Type",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
